[package]
edition = "2021"
name = "day18"
version = "0.1.0"

[features]

[dependencies]
env_logger = "0.9.0"
logging_timer = "1.0.0"
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.73"
