[package]
edition = "2021"
name = "day01"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_support = {path = "../aoc_support"}
itertools = "0.10.1"

[features]
